name: Motoko Unit Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'

    steps:
      - uses: actions/checkout@v2

      - name: Install vessel
        run: |
          set -x
          curl --location --output vessel-linux64 "https://github.com/dfinity/vessel/releases/download/v0.6.2/vessel-linux64"
          mkdir $HOME/bin
          mv ./vessel-linux64 $HOME/bin/vessel
          chown -R "$(whoami)" $HOME/bin && chmod -R +x $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run install canisters
        run: |
          set -x
          make test
